# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-11 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20180217_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_login',
            field=models.BooleanField(default=False),
        ),
    ]
