# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_userprofile_auto_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='c_name',
        ),
    ]
