# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20180417_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='c_name',
            new_name='name',
        ),
    ]
