# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20180417_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
